### ISSUE TITLE
Doesn't ever stop

### ISSUE THREAD

**Issue by mikestreety** [Jack000/SVGnest#11]
It doesn't seem to ever stop. I've had this running all day! :smile: 

Every now and then it will reshuffle, but it's always been at 66%. (This is using the demo SVG)

![screen shot 2016-01-22 at 17 33 45](https://cloud.githubusercontent.com/assets/354085/12518096/531cd7d2-c12e-11e5-9088-d15ade3e75c3.png)

**Comment by Neon22** [comment]
If infinite time is available :) you could loosen the constraint about biggest size down just a little - which might jostle them into an even tighter config.

Perhaps by having two versions of polygonarea().
One of which is used only for the order selection part and randomly returns a number "slightly smaller" than the real polygon area... ??

**Comment by Jack000** [comment]
so the biggest size thing is the starting point. The more iterations that are run, the farther you get away from that order via mutation.

material utilization is a bit misleading right now. The area used is just the sum of the area of all the parts divided by the area of the bin. Effectively it will be the same as long as the number of bins stays constant.

Should probably replace that with the are of the rectangular bounds, but the bin is not guaranteed to be rectangular so that wouldn't be completely accurate either. Think of the utilization number as a hint rather than a hard stat.

**Comment by leeoniya** [comment]
> but the bin is not guaranteed to be rectangular

no problem [1]

[1] http://www.codeproject.com/Articles/13467/A-JavaScript-Implementation-of-the-Surveyor-s-Form

**Comment by Jack000** [comment]
So to answer the original question (in case you weren't kidding). The solution space is too vast to find the exact optimal solution, so the GA continuously searches for better solutions until you tell it to stop.

As for the utilization parameter, the exact area is what it displays now. But I think using the rectangular bounds would be a better reflection of the quality of the nest.

**Comment by servant74** [comment]
Jack000,

I used to work for a company that did optimization solutions.  They had a 'good enough' limit to stop unlimited iterations.  Once you got within a half percent between iterations (if I remember right) it was considered 'good enough' nesting.  You might implement something like that, even with a settable 'good enough factor' (like default to .1% but allow any percent to be entered). ... Just a thought.

**Comment by Jack000** [comment]
yeah I guess that is a viable solution. I think this is more of a UX issue though - the expectation is that it will find a solution and stop, whereas the search is actually open-ended and could continue indefinitely.

I'm thinking a message could appear when nesting starts, that says something like "stop the program when you're satisfied with the solution"
