### ISSUE TITLE
Can't solve trivial problem.

### ISSUE THREAD

**Issue by lilezek** [Jack000/SVGnest#2]
I'm not sure if I drew it correctly, but this input:

![image](https://cloud.githubusercontent.com/assets/2767229/12373187/5cb440c6-bc71-11e5-8774-10fa52a0c3b0.png)

Produces this output after 700 iterations:

![image](https://cloud.githubusercontent.com/assets/2767229/12373189/68fc42de-bc71-11e5-9027-8a5cacbd47fb.png)

Forcing rotations to 1 thus decreasing incorrect combinations, and you can see there is one triangle left to be solved yet.

I attach here the svg zipped:

[test1.svg.zip](https://github.com/Jack000/SVGnest/files/92954/test1.svg.zip)

**Comment by lilezek** [comment]
It may not be clearly visible, but the triangle which is out of the solution, is the one at the center, just left upper from black square.

**Comment by ObeA** [comment]
Try playing around with the settings a bit. 
I solved it with 93% efficiency in < 193 iterations.
1; 0.3; 1; 10; 20; true. (order of options on http://svgnest.com/).

**Comment by Jack000** [comment]
I think it does eventually get it, but because the optimum solution is rather far from the initial decreasing size heuristic the GA needs to run for a while to discover it. I've had better luck with a higher mutation rate.

unfortunately this type of problem is basically the worst-case for the algo I'm using. It won't work well for cases with an exact optimal solution, or where a clear analytical solution exists (eg. a jigsaw puzzle)

the goal is to get close to the optimum by exploring a small fraction of the solution space and incrementally improving it via the GA. It will work best for cases like the demo - a mix of small and large parts, and a large number of parts.

There may be different algorithms that solve this type of problem better, it's definitely something I'll have to look into.

**Comment by lilezek** [comment]
I opened the issue assuming that could be there something wrong with the implementation.
