### ISSUE TITLE
possible to work with mm / metric sizes?

### ISSUE THREAD

**Issue by DanielRuf** [Jack000/SVGnest#25]
How can we use mm / cm measures for the bin and the objects which are nested and prevent any resizing and zooming?

**Comment by md1053** [comment]
Hi,
all my compliments to the project.
I stumbled on it because was looking for some open-source tool for nesting jobs for my company. Neither of the commercial software offer the constraints and options we are looking for. But I've found your way of input profiles not very usable. My shapes are in real dimensions too large for the screen, and so almost everything falls out of the screen (which also can't be scrolled horizontally)

**Comment by narvf** [comment]
I scale everything down in inkscape (for exeample 10 times smaller) then do nesting and reopen in inkscape and scale up ten times.

**Comment by Jack000** [comment]
hey guys

the nesting should stay true to the input svg. SVG is unitless so the exported nest is in whatever dimensions you defined in the input.

if you're finding that this is not the case, please send me the svg file.

the apparent size of the outlines in the browser is based on the svg workspace. Are you seeing the scaling problem on svgs exported from inkscape?

**Comment by narvf** [comment]
I think the problem is with big shapes 1:1 scale, they sometimes are very hard to see/click in browser.
After nesting scale is correct in my case. But i had 2 letters defrmed a little. 
And what about units with object spacing? In inkscape i set mm units and in after nesting looks like spacing is in pixels...

**Comment by Jack000** [comment]
hm.. ok. I could scale the view based on the actual contents of the file instead of the workspace.

the object spacing is defined in "pixels", where the conversion between pixels and real units is defined by the svg software, and is entirely arbitrary. For inkscape and illustrator it's 1/72 I believe. I'm not sure how to communicate this or to just assume a certain conversion.. but maybe I could add a tooltip so it's a bit more clear

**Comment by Jack000** [comment]
ok, I added some zoom buttons. Should cover cases where the content is too big/small compared to the workspace.

**Comment by narvf** [comment]
Great, thanks!
If it's not a problem you could add also in tooltip space in mm, 1/72 inch = 0.35mm :)

**Comment by Jack000** [comment]
done : ]
