### ISSUE TITLE
Slightly deformed shapes

### ISSUE THREAD

**Issue by narvf** [Jack000/SVGnest#27]
After nesting few elements (files attached) 2 shapes "S" and "W" letter was slightly different from original. 
Why this happened?

The second thing is, space in svgnest configuration was set to 10 (or 12 don't remember)  - svg was was set to mm in inkscape. And after nesting the space is around 3,5mm. 

![clipboard01](https://cloud.githubusercontent.com/assets/16607970/18383357/6d4c4266-7685-11e6-956e-eb98e8dbced1.jpg)

[zale.zip](https://github.com/Jack000/SVGnest/files/463723/zale.zip)

**Comment by Jack000** [comment]
when I open the original file in inkscape I see those squiggles on the letters, could you open up the exported svg and have a look? svgnest doesn't re-write paths but just rotate/displace the original path, so this type of problem is generally with the svg export software.

unfortunately svg doesn't have units, so the offset is in "pixels" and the conversion from pixels to real units is dependent on the exporting software. It's typically 72 or 92 pixels per inch. 10/72 inches = 3.5 mm so that sounds about right.

**Comment by narvf** [comment]
It looks like maybe i uploaded wrong file, i will take a look at home. But I'm afraid i don't have original file. Maybe in inkscape i made offset or something - hard to remember now :(
Thanks for suggestion about pixels/milimeters- yes some info on site would be nice :)

**Comment by Jack000** [comment]
alright, let me know if you see any other strangeness
